### ISSUE TITLE
npm package versions.

### ISSUE THREAD

**Issue by l3ok** [cognitive-catalyst/annotation-assist#1]
Hi

There are some conflicts with package versions. Corrected dependency:

"dependencies": {
    "babel-core": "^5.8.24",
    "babel-loader": "^5.3.2",
    "chunk-manifest-webpack-plugin": "0.0.1",
    "classnames": "^2.1.3",
    "css-loader": "^0.18.0",
    "d3": "^3.5.6",
    "file-loader": "^0.8.4",
    "history": "^1.9.1",
    "material-ui": "0.13.4",
    "moment": "^2.10.6",
    "react": "^0.14.0",
    "react-date-picker": "^3.1.3",
    "react-dom": "0.14.0",
    "react-tap-event-plugin": "0.2.0",
    "react-router": "1.0.1",
    "react-slider": "^0.5.1",
    "sass-loader": "^2.0.1",
    "style-loader": "^0.12.4",
    "url-loader": "^0.5.6"
  },

**Comment by thomasWatson** [comment]
Hey @l3ok can you detail the conflicts you're seeing? The dependencies install and build without problems over here.
