### ISSUE TITLE
db2 container in blumix is broken as of 20 May

### ISSUE THREAD

**Issue by amchaney** [cognitive-catalyst/annotation-assist#15]
An upgrade to the bluemix container environment has made it impossible to deploy the ibmcom/db2express-c - Docker image.

Annotation assist code will still work, but db2container instructions are now incorrect.

Remedy by either:
- [x] porting to yet ANOTHER db (that would be our third, thanks cloud computing!!)
- [x] forking the docker image so the process to start the db is in the initial run command (the reason in doesnt work anymore it because the ibm bluemix containers will now immediately shut down a container if it isn't running something, and the db2 docker image requires the run command to be initiated after the container is running due to a user permissions issue)
- [ ] something i haven't thought of yet

**Comment by amblock** [comment]
- db2 container issue has been resolved.
- aa now supports postgres
