### ISSUE TITLE
Incorrect project number in WEA URL doesn't generate an error message

### ISSUE THREAD

**Issue by wpm** [cognitive-catalyst/annotation-assist#2]
If you have an incorrect project number in the WEA URL specified in your `properties.ini` (e.g. the $14a5358a85f in https://watson.ihost.com/instance/115/predeploy/$14a5358a85f/wcea/api/GroundTruth/paus/) attempts to call the WEA instance for information about PAUs during PAU file upload will fail silently instead of giving a useful error message.

The problem appears to be that in this case XMGR doesn't return an error code, but rather an HTTP 200 with an HTML page explaining in text that there was a problem.

I don't know if this is the case for incorrect WEA URLs in general or just the case where your project number is wrong.

**Comment by amblock** [comment]
Direct WEA integration removed
